const fruits = [
  { name: 'durian' },
  { name: 'guava' },
  { name: 'lychee' },
  { name: 'passionfruit' },
  { name: 'kiwi' },
  { name: 'papaya' },
  { name: 'coconut' },
  { name: 'dragon fruit' },
  { name: 'pineapple' },
  { name: 'mango' },
  { name: 'prickly pear' },
  { name: 'banana' },
  { name: 'jackfruit' },
  { name: 'tamarind' },
  { name: 'star fruit' },
  { name: 'pomelo' },
  { name: 'avocado' },
  { name: 'acai' },
  { name: 'apple' },
  { name: 'orange' },
  { name: 'grapes' },
  { name: 'strawberry' },
  { name: 'melon' },
];

export default fruits;
