const fruits = [
  { name: 'durian', title: 'Durian' },
  { name: 'guava', title: 'Guava', imageSource: '' },
  { name: 'lychee', title: 'Lychee', imageSource: '' },
  { name: 'passionfruit', title: 'Passionfruit', imageSource: '' },
  { name: 'kiwi', title: 'Kiwi', imageSource: '' },
  { name: 'papaya', title: 'Papaya', imageSource: '' },
  { name: 'coconut', title: 'Coconut', imageSource: '' },
  { name: 'dragon fruit', title: 'Dragon fruit', imageSource: '' },
  { name: 'pineapple', title: 'Pineapple', imageSource: '' },
  { name: 'mango', title: 'Mango', imageSource: '' },
  { name: 'prickly pear', title: 'Prickly pear', imageSource: '' },
  { name: 'banana', title: 'Banana', imageSource: '' },
  { name: 'jackfruit', title: 'Jackfruit', imageSource: '' },
  { name: 'tamarind', title: 'Tamarind', imageSource: '' },
  { name: 'star fruit', title: 'Star fruit', imageSource: '' },
  { name: 'pomelo', title: 'Pomelo', imageSource: '' },
  { name: 'avocado', title: 'Avocado', imageSource: '' },
  { name: 'acai', title: 'Acai', imageSource: '' },
  { name: 'apple', title: 'Apple', imageSource: '' },
  { name: 'orange', title: 'Orange', imageSource: '' },
  { name: 'grapes', title: 'Grapes', imageSource: '' },
  { name: 'strawberry', title: 'Strawberry', imageSource: '' },
  { name: 'melon', title: 'Melon', imageSource: '' },
];

export default fruits;
